# Generated by Django 3.0.3 on 2020-07-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('current_skills', models.CharField(max_length=500)),
                ('aspiring_skills', models.CharField(max_length=500)),
                ('aspiring_role', models.CharField(max_length=100)),
                ('dream_company', models.CharField(max_length=100)),
                ('confirm_help', models.BooleanField()),
                ('confirm_signup', models.BooleanField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
